name: build container

on:
#  push:
#    branch: version_index

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "modulehandbook/modulehandbook"
  RAILS_MASTER_KEY: ${{ secrets.rails_master_key }}



jobs:
  test-and-push-image:
    name: just build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Base Image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: modhand-prod-no-assets
          push: false
          tags: modhand-prod-no-assets:latest
      - name: Build Test Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.testci
          target: modhand-testci
          push: false
          tags: modhand-testci:latest

      - name: Log in to the Container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set sha
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.sha.outputs.sha_short }}

      - name: Extract metadata (tags, labels) for Docker - PR
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,event=push
            type=semver, pattern={{version}}

      - name: Metadata Results
        run: |
           echo "---- tags:\n ${{ steps.meta.outputs.tags }}"
           echo "---- labels:\n ${{ steps.meta.outputs.labels }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: modhand-prod
          build-args: RAILS_MASTER_KEY=${{ secrets.rails_master_key }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
