
# build and (maybe) push docker image workflow called by  pipeline_02_structure.yml

name: dpb-action-v7

on:
  push:
    branches: update_rails_71
  #workflow_call:
  #  secrets:
  #    rails_master_key:
  #      required: false
  #    nudge:
  #      required: false
  #  inputs:
  #    tags:
  #      required: true
  #      type: string
  #    push:
  #      required: true
  #      type: boolean
  #    target:
  #      required: false
  #      type: string
  #      default: modhand-prod
  #    environment:
  #      required: false
  #      type: string
  #      default: staging


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: user/app:latest
